### ISSUE TITLE
ValueError: invalid literal for int() with base 10: ':1'

### ISSUE THREAD

**Issue by tzayuan** [dvlab-research/LLMGA#3]
sorry to bother you, but I meet the follow error when using gradio interface.
```
Traceback (most recent call last):
  File "/home/snowball/anaconda3/envs/llmga/lib/python3.9/site-packages/httpx/_urlparse.py", line 339, in normalize_port
    port_as_int = int(port)
ValueError: invalid literal for int() with base 10: ':1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/snowball/Documents/Code/LLMGA/llmga/serve/gradio_web_server.py", line 7, in <module>
    import gradio as gr
  File "/home/snowball/anaconda3/envs/llmga/lib/python3.9/site-packages/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "/home/snowball/anaconda3/envs/llmga/lib/python3.9/site-packages/gradio/components/__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "/home/snowball/anaconda3/envs/llmga/lib/python3.9/site-packages/gradio/components/annotated_image.py", line 13, in <module>
    from gradio import utils
  File "/home/snowball/anaconda3/envs/llmga/lib/python3.9/site-packages/gradio/utils.py", line 344, in <module>
    class AsyncRequest:
  File "/home/snowball/anaconda3/envs/llmga/lib/python3.9/site-packages/gradio/utils.py", line 363, in AsyncRequest
    client = httpx.AsyncClient()
  File "/home/snowball/anaconda3/envs/llmga/lib/python3.9/site-packages/httpx/_client.py", line 1408, in __init__
    self._mounts: typing.Dict[URLPattern, typing.Optional[AsyncBaseTransport]] = {
  File "/home/snowball/anaconda3/envs/llmga/lib/python3.9/site-packages/httpx/_client.py", line 1409, in <dictcomp>
    URLPattern(key): None
  File "/home/snowball/anaconda3/envs/llmga/lib/python3.9/site-packages/httpx/_utils.py", line 397, in __init__
    url = URL(pattern)
  File "/home/snowball/anaconda3/envs/llmga/lib/python3.9/site-packages/httpx/_urls.py", line 113, in __init__
    self._uri_reference = urlparse(url, **kwargs)
  File "/home/snowball/anaconda3/envs/llmga/lib/python3.9/site-packages/httpx/_urlparse.py", line 246, in urlparse
    parsed_port: typing.Optional[int] = normalize_port(port, scheme)
  File "/home/snowball/anaconda3/envs/llmga/lib/python3.9/site-packages/httpx/_urlparse.py", line 341, in normalize_port
    raise InvalidURL("Invalid port")
httpx.InvalidURL: Invalid port
```

Thanks

**Comment by Zj-BinXia** [comment]
It seems that the import Gradio reported an error. This is not my code issue, it's a problem with Gradio. I suggest Google it

**Comment by tzayuan** [comment]
I have solved this problem by manual install `gradio (3.50.2), graio_client(0.6.1) and httpx(0.26.0)` library before `pip install -e .` . Thanks!

**Comment by tzayuan** [comment]
Could you give me an example or some tips of inference using `llmga-llama-2-7b and llmga-sd15-t2i`? It seems that the provided code is adapted to sdxl, but not to sd15.

**Comment by Zj-BinXia** [comment]
Hi, I update my code for gradio on SD15 T2I. You can run it

python3 llmga.serve.gradio_web_server.py \
    --model-path ./checkpoints/llmga-llama-2-7b-chat-full-finetune  \
    --sdmodel_id ./checkpoints/llmga-sd15-t2i \
    --load-4bit \
    --model-list-mode reload \
    --port 8334 \

**Comment by tzayuan** [comment]
problem solved. Thanks!
